name: workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

env:
  GH_TOKEN: ${{ github.token }}
  TERM: xterm

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run script file
        run: sh watch.sh
