name: workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Git configuration
        run: |
          git config user.name "$(gh api /users/"${GITHUB_ACTOR}" | jq --raw-output .name)"
          git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Run script file
        run: sh watch.sh
